### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by janurskremer**
A few closing quotation marks were missing, which made reading a little confusing.

### CODE REVIEW

**Comment by acabal** [comment]
These are correct as-is. When the speaker's dialogue moves on to the next paragraph, the closing quote is omitted.

**Comment by janurskremer** [comment]
> These are correct as-is. When the speaker's dialogue moves on to the next paragraph, the closing quote is omitted.

Why are there new opening quotation marks then? Is this common in English? I’ve never seen it like this in German.

**Comment by acabal** [comment]
Yes, this is standard English typography. Typography differs across languages, which is why SE only works with English-language books.

**Comment by acabal** [comment]
See for example https://baxtercommunications.nl/quotation-marks-multi-paragraph-rule/

**Pull request closed without merging**
